name: Synchronize to react-para-la-raza

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '**/docs/**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          token: ${{ secrets.API_TOKEN_FOR_REACTPARALARAZA_UI }}

      - name: Push to Destination Repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_FOR_REACTPARALARAZA_UI }}
        with:
          source-directory: 'path/to/sync/directory'
          destination-github-username: 'juanmgomez7152'
          destination-repository-name: 'react-para-la-raza'
          user-email: 'sync-bot@github.com'
          user-name: 'github-actions[bot]'
          target-branch: 'master'
          commit-message: 'Automated sync: ${{ github.sha }}'